//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Nota.CharacterGenerator.CoreData.Kampf.Aktionen
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;



    /// <summary>
    public partial class Aktionen
    {

    }

    public partial class AktionenAktion
    {

    }

    public partial class AktionenAktionMod
    {
    }

    public partial class ConcreteModValueType
    {
    }

    public partial class VariableModValueType
    {
    }

    public partial class AddModValueType
    {
    }

    public partial class MultiplyModValueType
    {
    }
}
