//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.58.0.
namespace Nota.CharacterGenerator.CoreData.Misc
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Xml.Serialization;



    public partial class NamedType : INamedElement
    {

        public LevelsLevel ToLevel(Kultur.KulturenKultur kultur)
        {
            return kultur.Levels.FirstOrDefault(l => l.Name == this.Name);
        }
        public LevelsLevel ToLevel(Profession.ProfessionenProfession profession)
        {
            return profession.Levels.FirstOrDefault(l => l.Name == this.Name);
        }


        public static implicit operator Besonderheit.BesonderheitenBesonderheit(NamedType reference)
        {
            return Root.Daten.Besonderheiten.FirstOrDefault(x => x.Name == reference.Name);
        }

    }


    public partial class NamedTypeReqiredeValue : NamedType
    {
    }

    public partial class NamedTypeOptionalValue : NamedType
    {
    }

    public partial class LevelAuswahl
    {
    }

    public partial class LevelAuswahlen
    {
    }

    public partial class And : LevelAuswahlen
    {
    }

    public partial interface IKostenElement
    {

    }

    public partial class Levels
    {
    }

    /// <summary>
    public partial class LevelsLevel : Nota.CharacterGenerator.CoreData.Misc.IKostenElement
    {
    }

    public partial class LevelsLevelBedingungen
    {
    }
}
